# Fetching the minified node image on apline linux
FROM node:20.12-alpine3.19 AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Set environment variable for Vite build
ARG VITE_API_URL=http://loclahost:3000
ENV VITE_API_URL=$VITE_API_URL

# Build the Vite app
RUN npm run build

# Use a lightweight server to serve the built app
FROM nginx:alpine

# Set environment variables for Nginx
ENV VIRTUAL_HOST=your-domain  
ENV LETSENCRYPT_HOST=your-domain

# Copy the built files from the previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
