# Stage 1: Install dependencies and build Prisma client
FROM node:18 AS builder

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install

# Install Prisma CLI globally for migrations and process management
RUN npm install -g prisma

# Copy the rest of the application code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Stage 2: Production image
FROM node:18

WORKDIR /app

# Declaring env
# ARG NODE_ENV=development
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

ENV AZURE_STORAGE_CONNECTION_STRING=PLACEHOLDER_CONNECTION_STRING
ENV DATABASE_URL="DB://USER:PASSWORD@IP:PORT/DB_NAME"
ENV AZURE_STORAGE_CONTAINER=dev-container
ENV VIRTUAL_HOST=PUT_YOUR_DOMAIN
ENV LETSENCRYPT_HOST=PUT_YOUR_DOMAIN

# Install PM2 globally in the production image
RUN npm install -g pm2

# Copy only the node_modules and prisma client from the builder stage
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma

RUN npm install -g prisma
RUN npx prisma generate

# Copy the rest of the application code
COPY --from=builder /app ./

# Expose the port Fastify will run on
EXPOSE 3000

# Command to start the application
CMD ["sh", "-c", "npx prisma migrate deploy && pm2 start process.yml && tail -f /dev/null"]